-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- function _G.set_terminal_keymaps()
--   local opts = { buffer = 0 }
--
--   vim.keymap.set("t", "<esc>", "<c-\\><c-n>", opts)
--   vim.keymap.set("t", "<C-h>", "<cmd>wincmd h<cr>", opts)
--   vim.keymap.set("t", "<C-j>", "<cmd>wincmd j<cr>", opts)
--   vim.keymap.set("t", "<C-k>", "<cmd>wincmd k<cr>", opts)
--   vim.keymap.set("t", "<C-l>", "<cmd>wincmd l<cr>", opts)
--   vim.keymap.set("t", "<C-w>", [[<c-\><c-n><c-w>]], opts)
-- end
--
-- -- if you only want these mappings for toggle term use term://*toggleterm#* instead
-- vim.cmd("autocmd! TermOpen term://* lua set_terminal_keymaps()")
